version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_8
    #build:
    #  context: ./docker-config
    #  dockerfile: docker-config/Dockerfile
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#    command:
#      - /bin/bash
#      - -c
#      - |
#        mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./storage/db/data:/var/lib/mysql
    environment:
      TZ: ${TIMEZONE-"Asia/Taipei"}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:3306"
    networks:
      - local-network


networks:
  local-network:
    driver: bridge
