---

- name: "staging    ({{ CI_BRANCH }}) -> {{ DEPLOY_TO }}"
  hosts: deploy-staging
  vars_files:
    - env.yml
  vars:
    CI_BRANCH:                                "master"
    ansible_user:                             "ubuntu"
    ansistrano_deploy_to:                     "{{ DEPLOY_TO }}"
    ansistrano_git_repo:                      "{{ REPO }}"
    ansistrano_git_branch:                    "{{ CI_BRANCH }}"
    ansistrano_git_identity_key_path:         "{{ GIT_IDENTITY_KEY_PATH }}"
    ansistrano_deploy_via:                    git
    ansistrano_keep_releases:                 3
    ansistrano_before_setup_tasks_file:       "tasks/init.yml"
    ansistrano_after_update_code_tasks_file:  "tasks/pull-after.yml"
    ansistrano_before_symlink_tasks_file:     "tasks/pre-deploy-for-docker.yml"
    ansistrano_after_symlink_tasks_file:      "tasks/post-deploy.yml"
    ansistrano_shared_paths:
      - node_modules
      - storage
    ansistrano_shared_files:
      - .env


  tasks:


  roles:
   - { role: ansistrano.deploy, tags: deploy }

