---

- name: "localhost  ({{ CI_BRANCH }}) -> {{ DEPLOY_TO }}"
  hosts: deploy-local
  vars_files:
    - env.yml
  vars:
    CI_BRANCH:                                "master"
    ansible_user:                             "ubuntu"
    ansistrano_deploy_to:                     "{{ DEPLOY_TO }}"
    ansistrano_git_repo:                      "{{ REPO }}"
    ansistrano_git_branch:                    "{{ CI_BRANCH }}"
    ansistrano_git_identity_key_path:         ""
    ansistrano_deploy_via:                    git
    ansistrano_keep_releases:                 3
    ansistrano_before_setup_tasks_file:       "tasks/init.yml"
    ansistrano_after_update_code_tasks_file:  "tasks/pull-after.yml"
    ansistrano_before_symlink_tasks_file:     "tasks/pre-deploy.yml"
    ansistrano_after_symlink_tasks_file:      "tasks/post-deploy.yml"
    ansistrano_shared_paths:
      - node_modules
      - storage
    ansistrano_shared_files:
      - .env


  tasks:

#    - debug: msg="==== start ===="

#    - name: set DB_DATABASE
#      lineinfile: dest=.env.example regexp='^DB_DATABASE=' line=DB_DATABASE=laravel
#    - debug: msg="APP_NAME={{ DB_DATABASE }} by env.yml"

    - name: aaa
      shell:
        echo date
        echo 'hello world 2'
      args:
        executable: /bin/bash

    - name: ccc
      shell:
        echo 123

#
#   - name: Check package.json file
#     stat:
#       path: "{{ ansistrano_release_path.stdout }}/package.json"
#     register: project_npm
#
#   - name: Run npm install
#     npm:
#       path: "{{ ansistrano_release_path.stdout }}"
#     when: project_npm.stat.exists
#
#   - name: "Check if .env exists locally"
#     local_action: stat path=".env"
#     register: result
#
#   - name: "Check if .env.example exists locally"
#     local_action: stat path=".env.example"
#     register: result


  roles:
   - { role: ansistrano.deploy, tags: deploy }
   # @see https://github.com/ansistrano/deploy
