- name: pre-deploy
  debug: msg="====== pre-deploy ======"


- name: laravel storage directories create
  file:
    path: "{{ ansistrano_shared_path }}/storage/{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - app
    - app/public
    - logs
    - framework
    - framework/cache
    - framework/sessions
    - framework/views

- name: laravel shared directories permissions
  command: find {{ ansistrano_shared_path }} -type d -exec chmod 775 {} \;

- name: laravel shared files permissions
  command: find {{ ansistrano_shared_path }} -type f -exec chmod 664 {} \;

- name: composer install (docker)
  shell: |
    cd {{ ansistrano_release_path.stdout }}
    docker exec fs-marketing-tool_php7_1 composer install

- name: laravel rebuild object cache (docker)
  shell: |
    cd {{ ansistrano_release_path.stdout }}
    docker exec fs-marketing-tool_php7_1 php artisan storage:link

- name: laravel migrate (docker)
  shell: |
    cd {{ ansistrano_release_path.stdout }}
    docker exec fs-marketing-tool_php7_1 php artisan migrate # --force
    
